# Generated by Django 2.1 on 2018-10-05 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(null=True)),
                ('checkin_complete', models.BooleanField(default=False)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('current_meds', models.CharField(default='None', max_length=250)),
                ('past_history', models.CharField(default='None', max_length=250)),
                ('current_complaints', models.CharField(default='None', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albendazole', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('fluoride_varnish', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('meds_administered', models.CharField(default='N/A', max_length=100)),
                ('followup', models.CharField(default='N/A', max_length=100)),
                ('check_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientRecords.CheckIn')),
            ],
        ),
        migrations.CreateModel(
            name='EyeCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_complete', models.BooleanField(default=False)),
                ('od', models.IntegerField(blank=True)),
                ('os', models.IntegerField(blank=True)),
                ('near', models.CharField(blank=True, max_length=100)),
                ('pinhole', models.CharField(blank=True, max_length=100)),
                ('exam_notes', models.CharField(blank=True, max_length=250)),
                ('assessment', models.CharField(blank=True, max_length=250)),
                ('plan', models.CharField(blank=True, max_length=250)),
                ('check_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientRecords.CheckIn')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('school_grade', models.CharField(blank=True, max_length=15)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neither', 'Neither')], default='Neither', max_length=7)),
                ('school', models.CharField(choices=[('Santa Maria', 'Santa Maria'), ('San Jose', 'San Jose'), ('Prepa', 'Prepa'), ('Staff', 'Staff'), ('None', 'None')], default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VisitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_complete', models.BooleanField(default=False)),
                ('heent', models.CharField(default='NC/AT; TMs clear; PERRL; Nares clear; Tonsils nml; Teeth nml', max_length=200)),
                ('neck_nodes', models.CharField(default='No sig. adenopathy, Neck nml; Thyroid nml', max_length=200)),
                ('chest_heart', models.CharField(default='Lungs clear; No murmur; Reg rate and rhythm', max_length=200)),
                ('abdomen', models.CharField(default='soft/flat; bowel sounds active; no hepatosplenomegaly', max_length=200)),
                ('extremities', models.CharField(default='Normal upper and lower ext; normal range of motion', max_length=200)),
                ('spine', models.CharField(default='Straight; normal flexion/extension', max_length=200)),
                ('skin', models.CharField(default='Warm/dry; no rash', max_length=200)),
                ('neuro', models.CharField(default='Alert and oriented; Strength sym and nml; Gait nml; Pat DTR nml', max_length=200)),
                ('teeth', models.CharField(default='Normal dentition', max_length=200)),
                ('visit_notes', models.CharField(max_length=500)),
                ('meds_perscribed', models.CharField(blank=True, default='None', max_length=100)),
                ('follow_up_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('check_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientRecords.CheckIn')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo')),
            ],
        ),
        migrations.AddField(
            model_name='eyecare',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
    ]
