# Generated by Django 2.0.2 on 2018-02-27 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('school_grade', models.CharField(blank=True, max_length=15)),
                ('school', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Neither', 'Neither')], default='Neither', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_of_checkin', models.DateTimeField(blank=True, verbose_name='Time of Checkin')),
                ('date_time_of_visit', models.DateTimeField(blank=True, verbose_name='Time of Exam')),
                ('date_time_of_checkout', models.DateTimeField(blank=True, verbose_name='Time of Checkout')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo')),
            ],
        ),
    ]
