# Generated by Django 2.1 on 2018-10-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitinfo',
            name='visit_notes',
        ),
        migrations.AddField(
            model_name='visitinfo',
            name='assessment',
            field=models.CharField(default='Healthy', max_length=500),
        ),
    ]
