# Generated by Django 2.0.2 on 2018-02-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0002_auto_20180226_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='bmi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='current_complaints',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='checkin',
            name='current_meds',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='checkin',
            name='diastolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='past_history',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='checkin',
            name='systolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
