# Generated by Django 2.1 on 2018-10-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0003_auto_20181020_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyecare',
            name='exam_notes',
            field=models.CharField(default='P; VF; MB; Penlight; VFE', max_length=250),
        ),
    ]
