# Generated by Django 2.0.2 on 2018-02-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0005_auto_20180226_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_of_checkout', models.DateTimeField(verbose_name='Time of checkout')),
                ('od', models.IntegerField(blank=True)),
                ('os', models.IntegerField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo')),
            ],
        ),
    ]
