# Generated by Django 2.0.2 on 2018-02-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0006_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitinfo',
            name='meds_perscribed',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitinfo',
            name='visit_notes',
            field=models.CharField(max_length=500),
        ),
    ]
