# Generated by Django 2.0.2 on 2018-02-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0007_auto_20180226_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='albendazol',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='checkout',
            name='fluoride_varnish',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='checkout',
            name='followup',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='meds_administered',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
