# Generated by Django 2.0.2 on 2018-03-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0008_auto_20180226_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.IntegerField(blank=True)),
                ('os', models.IntegerField(blank=True)),
                ('near', models.CharField(blank=True, max_length=100)),
                ('pinhole', models.CharField(blank=True, max_length=100)),
                ('exam_notes', models.CharField(blank=True, max_length=250)),
                ('assessment', models.CharField(blank=True, max_length=250)),
                ('plan', models.CharField(blank=True, max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='od',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='os',
        ),
    ]
