# Generated by Django 2.0.2 on 2018-03-04 06:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0010_auto_20180303_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='patient',
            field=models.ForeignKey(default=datetime.datetime(2018, 3, 3, 23, 26, 7, 992665), on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='school',
            field=models.CharField(choices=[('Santa Maria', 'Santa Maria'), ('San Jose', 'San Jose'), ('Prepa', 'Prepa'), ('None', 'None')], max_length=20),
        ),
    ]
