# Generated by Django 2.0.2 on 2018-03-15 03:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0012_auto_20180311_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='patient',
            field=models.ForeignKey(default=datetime.datetime(2018, 3, 14, 21, 39, 28, 625560), on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='school',
            field=models.CharField(choices=[('Santa Maria', 'Santa Maria'), ('San Jose', 'San Jose'), ('Prepa', 'Prepa'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
