# Generated by Django 2.0.2 on 2018-03-24 04:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0016_auto_20180323_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='current_complaints',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='current_meds',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='past_history',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='patient',
            field=models.ForeignKey(default=datetime.datetime(2018, 3, 23, 22, 46, 34, 16779), on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
    ]
