# Generated by Django 2.0.2 on 2018-04-03 01:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0018_auto_20180325_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='date_time_of_checkin',
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_complete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='patient',
            field=models.ForeignKey(default=datetime.datetime(2018, 4, 2, 19, 10, 29, 969624), on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
    ]
