# Generated by Django 2.0.2 on 2018-04-04 22:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0019_auto_20180402_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='patient',
            field=models.ForeignKey(default=datetime.datetime(2018, 4, 4, 16, 20, 45, 618247), on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
    ]
