# Generated by Django 2.0.2 on 2018-04-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0020_auto_20180404_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientRecords.PatientInfo'),
        ),
    ]
