# Generated by Django 2.0.2 on 2018-04-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0021_auto_20180404_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitinfo',
            name='date_time_of_visit',
        ),
        migrations.AddField(
            model_name='visitinfo',
            name='checkup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
