# Generated by Django 2.0.2 on 2018-04-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0022_auto_20180404_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyecare',
            name='date_time_of_eye_exam',
        ),
        migrations.AddField(
            model_name='eyecare',
            name='checkout_complete',
            field=models.BooleanField(default=False),
        ),
    ]
