# Generated by Django 2.0.2 on 2018-04-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0023_auto_20180415_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='date_time_of_checkout',
        ),
    ]
