# Generated by Django 2.1 on 2018-08-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0025_visittracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visittracker',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='VisitTracker',
        ),
    ]
