# Generated by Django 2.1 on 2018-10-05 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecords', '0026_auto_20180826_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='current_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='checkout',
            name='check_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientRecords.CheckIn'),
        ),
        migrations.AddField(
            model_name='eyecare',
            name='check_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientRecords.CheckIn'),
        ),
        migrations.AddField(
            model_name='visitinfo',
            name='check_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientRecords.CheckIn'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='school',
            field=models.CharField(choices=[('Santa Maria', 'Santa Maria'), ('San Jose', 'San Jose'), ('Prepa', 'Prepa'), ('Staff', 'Staff'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
